/* Landing only: composition based on artboard 1 of itaso_landing_editable2.ai. */
(function () {
  const paths = {
    arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
    search:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/>',
    apple:'<path d="M5 10c-2-5 3-7 7-4 5-3 9-1 8 5-1 7-5 10-8 8-5 3-9-3-7-9Zm7-4c0-4 2-5 5-5"/>',
    brain:'<path d="M12 5c-3-5-9-1-8 4-4 3-2 8 1 8 0 5 7 6 7 2V5Zm0 0c3-5 9-1 8 4 4 3 2 8-1 8 0 5-7 6-7 2M6 9l3 2m-3 5 3-2m9-5-3 2m3 5-3-2"/>',
    book:'<path d="M12 5C8 2 4 3 2 4v16c4-1 7 0 10 2 3-2 6-3 10-2V4c-4-1-7-2-10 1Zm0 0v17"/>',
    leaf:'<path d="M12 22V9m0 5C3 14 3 3 3 3s10-1 9 11Zm0 4c0-8 10-10 10-10s0 10-10 10Z"/>',
    target:'<circle cx="11" cy="13" r="10"/><circle cx="11" cy="13" r="6"/><circle cx="11" cy="13" r="1"/><path d="m11 13 11-11m-4 0h4V0"/>',
    file:'<path d="M5 1h9l6 6v16H5V1Zm9 0v6h6M8 12h9m-9 5h9"/>'
  };
  const icon = name => `<svg class="lp-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`;
  const wave = (kind) => kind === 'yellow' ? `<svg class="lp-wave lp-wave--yellow" viewBox="0 0 1440 100" preserveAspectRatio="none" aria-hidden="true"><path d="M0 0h1440v43c-80-68-130-24-210-6-142 40-235 20-340-20-145-55-196 20-300 29C425 84 334 7 215 3 115-9 54 8 0 33Z"/></svg>` : `<svg class="lp-wave lp-wave--${kind}" viewBox="0 0 1440 100" preserveAspectRatio="none" aria-hidden="true"><path d="M0 28C220-16 378 70 606 38c250-37 432 37 630-9 95-23 159-16 204 1v70H0Z"/></svg>`;
  const teamCard = (name,description,image,kind,cta,action) => `<article class="lp-card"><img class="lp-card-photo" src="assets/identity/itaso_landing_editable-${image}.png" alt="" loading="lazy"><div class="lp-card-content"><span class="lp-card-icon lp-tone-${kind}">${icon(kind)}</span><h3>${name}</h3><p>${description}</p><button class="lp-button lp-button--text lp-tone-${kind}" type="button" ${action}>${cta}${icon('arrow')}</button></div></article>`;
  function navigation() { return `<button type="button" class="lp-menu-toggle" data-lp-menu aria-controls="lp-nav-links" aria-expanded="false">Menú <span aria-hidden="true">☰</span></button><div id="lp-nav-links" class="lp-nav-links"><a href="#quienes" data-lp-scroll="quienes">Quiénes somos</a><a href="#equipo" data-lp-scroll="equipo">Equipo</a><a href="#mision" data-lp-scroll="mision">Misión y visión</a><a href="#fuentes" data-lp-scroll="fuentes">Fuentes</a><button class="lp-search-toggle" type="button" data-lp-search aria-label="Buscar en esta página">${icon('search')}</button><a class="lp-button lp-button--primary" href="#quienes" data-lp-scroll="quienes">Conócenos</a></div>`; }
  function markup() { return `
    <section class="lp-hero lp-container" aria-labelledby="lp-title"><div class="lp-hero-copy"><p class="lp-eyebrow">Instituto de Trastornos y Alimentación Saludable</p><h1 id="lp-title">Claridad para<br>decidir desde<br>tu realidad.</h1><p class="lp-lead">Información comprensible y herramientas prácticas para acompañar decisiones cotidianas sobre alimentación, bienestar y movimiento.</p><div class="lp-actions"><a class="lp-button lp-button--orange" href="#quienes" data-lp-scroll="quienes">Conócenos ${icon('arrow')}</a><button class="lp-button lp-button--secondary" type="button" data-open-audience>Elegir experiencia</button></div></div><div class="lp-hero-media"><img src="assets/identity/itaso_landing_editable-1.png" alt="Una madre abraza a su hija" fetchpriority="high" width="526" height="521"></div></section>
    <div class="lp-blue-band" aria-hidden="true"><svg class="lp-wave lp-wave--ribbon" viewBox="0 0 1440 116" preserveAspectRatio="none"><path d="M0 15C220-29 378 58 606 26c250-37 432 37 630-9 95-23 159-16 204 1v88c-50-24-112-24-204-1-198 46-380-28-630 9C378 146 220 59 0 103Z"/></svg></div>
    <section id="quienes" class="lp-about"><div><p class="lp-eyebrow">Quiénes somos</p><h2>Ciencia que se puede<br>usar en la vida real</h2></div><p>ITASO-MX transforma evidencia científica en criterios claros para que niñas, niños, adolescentes y sus cuidadores puedan comparar alternativas y tomar decisiones posibles, sin juicios ni respuestas únicas.</p></section>
    <section id="equipo" class="lp-team">${wave('orange')}<div class="lp-team-surface"><p class="lp-eyebrow">Equipo</p><h2>Una mirada integral</h2><div class="lp-team-grid">${teamCard('Nutrición','Contenido basado en evidencia y lenguaje cotidiano.',2,'apple','Explorar','data-lp-info="nutrition"')}${teamCard('Psicología','Orientación respetuosa, libre de estigma.',3,'brain','Conoce al equipo','data-lp-info="team"')}${teamCard('Educación','Herramientas útiles para aprender haciendo.',4,'book','Explorar','data-open-audience')}</div></div>${wave('orange-bottom')}</section>
    <section id="mision" class="lp-purpose lp-container"><article class="lp-purpose-card"><span class="lp-purpose-icon">${icon('leaf')}</span><div><p class="lp-eyebrow">Misión</p><h2>Acompañar</h2><p>Convertir información compleja en decisiones comprensibles y aplicables.</p></div></article><article class="lp-purpose-card lp-purpose-card--vision"><span class="lp-purpose-icon">${icon('target')}</span><div><p class="lp-eyebrow">Visión</p><h2>Bienestar posible</h2><p>Entornos donde el cuidado se construya con autonomía, criterio y empatía.</p></div></article></section>
    <section id="fuentes" class="lp-sources">${wave('yellow')}<div class="lp-container lp-sources-content"><div><p class="lp-eyebrow">Fuentes</p><h2>Transparencia científica</h2><p>Este sitio reserva un espacio para referencias, notas<br class="lp-desktop-break"> metodológicas y actualización de contenidos.</p></div><button class="lp-button lp-button--source" type="button" data-lp-info="sources">${icon('file')} Ver todas las fuentes</button></div></section>
    <footer class="lp-footer lp-container"><div><a href="#/inicio" aria-label="ITASO-MX, inicio"><img src="assets/identity/logo-color.svg" alt="ITASO-MX" width="260" height="95"></a><p>© ITASO-MX — prototipo</p></div><nav aria-label="Información legal"><button type="button" data-lp-info="privacy">Privacidad</button><button type="button" data-lp-info="terms">Términos</button><a href="mailto:contacto@itaso.mx">Contacto</a></nav></footer>
    <dialog id="lp-dialog" class="lp-dialog" aria-labelledby="lp-dialog-title"><button class="lp-dialog-close" type="button" data-lp-close aria-label="Cerrar">×</button><h2 id="lp-dialog-title"></h2><div id="lp-dialog-content"></div></dialog>`; }
  const info = {
    nutrition:['Nutrición','Contenido basado en evidencia y lenguaje cotidiano. Puedes explorar los temas disponibles en la experiencia para cuidadores.','<a class="lp-button lp-button--primary" href="#/cuidadores/alimentacion">Ver temas de alimentación</a>'],
    team:['Una mirada integral','El prototipo reúne las áreas de nutrición, psicología y educación. Los perfiles individuales del equipo están pendientes de integración.',''],
    sources:['Fuentes científicas','Las referencias, notas metodológicas y fechas de actualización están pendientes de integración en este prototipo.',''],
    privacy:['Privacidad','La política de privacidad está pendiente de publicación. Esta vista es un prototipo.',''],
    terms:['Términos','Los términos de uso están pendientes de publicación. Esta vista es un prototipo.','']
  };
  function openInfo(title,html) { const dialog=document.querySelector('#lp-dialog'); if(!dialog) return; document.querySelector('#lp-dialog-title').textContent=title; document.querySelector('#lp-dialog-content').innerHTML=html; dialog.showModal(); }
  document.addEventListener('click',event=>{
    if (!document.querySelector('.landing-page')) return;
    const scroll=event.target.closest('[data-lp-scroll]');
    if(scroll) {event.preventDefault(); document.querySelector('#lp-dialog')?.close(); const target=document.getElementById(scroll.dataset.lpScroll); target?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}); document.querySelector('[data-lp-menu]')?.setAttribute('aria-expanded','false');}
    const menu=event.target.closest('[data-lp-menu]'); if(menu) menu.setAttribute('aria-expanded',String(menu.getAttribute('aria-expanded')!=='true'));
    const item=event.target.closest('[data-lp-info]'); if(item) {const [title,description,link]=info[item.dataset.lpInfo];openInfo(title,`<p>${description}</p>${link}`);}
    if(event.target.closest('[data-lp-close]')) document.querySelector('#lp-dialog').close();
    if(event.target.closest('[data-lp-search]')) openInfo('Buscar en esta página','<label for="lp-query">Tema o sección</label><input id="lp-query" type="search" placeholder="Por ejemplo: equipo o fuentes"><div id="lp-search-results" role="status"></div>');
  });
  document.addEventListener('input',event=>{ if(event.target.id!=='lp-query') return; const query=event.target.value.trim().toLocaleLowerCase('es'); const sections=[['quienes','Quiénes somos · Ciencia y alimentación'],['equipo','Equipo · Nutrición, psicología y educación'],['mision','Misión y visión'],['fuentes','Fuentes científicas']]; const matches=sections.filter(([,name])=>name.toLocaleLowerCase('es').includes(query)); document.querySelector('#lp-search-results').innerHTML=matches.length?matches.map(([id,name])=>`<a href="#${id}" data-lp-scroll="${id}">${name}</a>`).join(''):'<p>No hay coincidencias. Prueba con otra palabra.</p>'; });
  window.ITASO_LANDING={markup,navigation};
})();
